services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/var/www/app
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/app
  couchbase:
    image: couchbase/server-sandbox:7.1.1
    ports:
      - 8091-8094:8091-8094
      - 11210:11210